version: "3.9"

networks:
  dev-network:
    driver: bridge

services:
  database:
    image: 4s4v1n/comment_system_database
    container_name: html_comment_system_db
    ports:
      - "5400:5432"
    restart: always
    networks:
      - dev-network

  backend:
    image: 4s4v1n/comment_system_backend
    container_name: html_comment_system_backend
    ports:
      - "8080:8080"
    restart: always
    networks:
      - dev-network
    depends_on:
      - database

  fronted:
    image: 4s4v1n/comment_system_frontend
    container_name: html_comment_system_frontend
    ports:
      - "3000:3000"
    restart: always
    networks:
      - dev-network
    depends_on:
      - backend
