version: "3.9"

networks:
  dev-network:
    driver: bridge

services:
  db:
    image: postgres:latest
    container_name: html_comment_system_db
    ports:
      - "5400:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: html_comments
    restart: always
    networks:
      - dev-network

  fronted:
    container_name: html_comment_system_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    networks:
      - dev-network
    depends_on:
      - backend

  backend:
    container_name: html_comment_system_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - dev-network
    depends_on:
      - db
